### PR TITLE
Feat EndOfGame styling

### PR DESCRIPTION
**Pull request by iccir919**
Ignore the branch name. Not sure how to not make EntryListItem not stretch the whole window
screen shot 2017-03-25 at 8 05 36 pm

### CODE REVIEW

**Comment by iccir919** [comment]
additionally there is a change in db/index.js here that i couldn't ignore in this request cause i committed in my master branch i believe

**Review by smclendening — CHANGES_REQUESTED** [review]
Hey Neil, nice start. To make each item not stretch to the entire window, you'll want to use the <Col> component from React-Bootstrap - here's an explanation from their docs: https://react-bootstrap.github.io/components.html#grid  

Also for an example on how we've been using the <Col> components, I would look at the render function of the PlayingGame component. To keep things consistent, it's probably best to use something like the following: <Col sm={6} smOffset={3}>. 

Also, it looks like there are a few quotation marks we want to take out - for example, the Prompt in the header. 

Let me know if you have any questions!

**Comment by iccir919** [comment]
@smclendening i believe i fixed your mentioned issues. let me know if theres anything else

**Comment by iccir919** [comment]
screen shot 2017-03-26 at 1 17 34 pm

**Review by smclendening — CHANGES_REQUESTED** [review]
Hey Neil, nice work. One last thing - since we modified the Winner component (what everyone sees after the Judge selects a winner) to use colors in addition to text to show who the Winner was, we should probably stay consistent and do the same here. Could you please update the RoundSummary component so that it has the same style as the Winner component (same coloring for winner vs non-winners, and same order of contents. Here's an example of what I mean - basically, make the RoundSummary component look like the results here: 

screen shot 2017-03-26 at 1 14 33 pm

Oh and also, we still want to have a Button at the bottom which allows users to return to the lobby.

**Comment by iccir919** [comment]
screen shot 2017-03-26 at 3 32 17 pm
screen shot 2017-03-26 at 3 32 05 pm

**Review by pmillssf — CHANGES_REQUESTED** [review]
Hey Neil, could you style the header above each of the responses. Right now the way that "Prompt: prompt 4 Judge:Wait1" and "Responses" appear seems a bit thrown together. Maybe remove the 'Responses' heading all together and then stack the judge on top of the prompt.

**Comment by iccir919** [comment]
screen shot 2017-03-26 at 7 02 35 pm

**Review by smclendening — APPROVED** [review]
Nice work

**Pull request merged**
